username: mabercx
port: 22
look_for_keys: True
key_filename: ~/.ssh/id_ed-lumi
timeout: 60
allow_agent: True
proxy_command: ''
proxy_jump: ''
compress: True
gss_auth: False
gss_kex: False
gss_deleg_creds: False
gss_host: lumi.csc.fi
load_system_host_keys: True
key_policy: RejectPolicy
use_login_shell: True
safe_interval: 10.0
