port: 22
look_for_keys: True
timeout: 60
allow_agent: True
proxy_command: False  # Note: For Piz daint it is recommended to use the `proxy_jump` setting
compress: True
gss_auth: False
gss_kex: False
gss_deleg_creds: False
gss_host: daint.cscs.ch
load_system_host_keys: True
key_policy: RejectPolicy
use_login_shell: True
safe_interval: 30.0
