port: 22
look_for_keys: True
timeout: 60
allow_agent: True
proxy_jump: ''
compress: True
gss_auth: False
gss_kex: False
gss_deleg_creds: False
gss_host: eiger.cscs.ch
load_system_host_keys: True
key_policy: RejectPolicy
use_login_shell: False
safe_interval: 10